Traceback (most recent call last):
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\dudas\anaconda3\envs\wintest\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print( "aVar=", aVar, "; bVar =", bVar, "; cVar = ", cVar )

# Is aVar equal to 10?
print( "\n#-# Is aVar equal to 10?")
print( aVar == 10 )
      
# Is aVar equal to bVar?
print( "\n#-# Is aVar equal to bVar?" )
print( aVar == bVar )

# Is aVar equal to cVar?
print( "\n#-# Is aVar equal to cVar?" )
print( aVar == cVar )

# Is aVar equal to 10 AND aVar equal to bVar?
print ( "\n#-# Is aVar equal to 10 AND aVar equal to bVar?")
print( (aVar == 10) and (aVar == bVar) )

# Is aVar equal to 10 AND aVar equal to cVar?
print ( "\n#-# Is aVar equal to 10 AND aVar equal to cVar?")
print( (aVar == 10) and (aVar == cVar) )


------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-10-8f6a33a6d569>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mprint[0m[1;33m([0m [1;34m"aVar="[0m[1;33m,[0m [0maVar[0m[1;33m,[0m [1;34m"; bVar ="[0m[1;33m,[0m [0mbVar[0m[1;33m,[0m [1;34m"; cVar = "[0m[1;33m,[0m [0mcVar[0m [1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;33m[0m[0m
[0;32m      3[0m [1;31m# Is aVar equal to 10?[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mprint[0m[1;33m([0m [1;34m"\n#-# Is aVar equal to 10?"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0mprint[0m[1;33m([0m [0maVar[0m [1;33m==[0m [1;36m10[0m [1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'aVar' is not defined
NameError: name 'aVar' is not defined

